/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 06338b25-76ba-42c4-ade3-e3401b6db211

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a cohesion-sensitive power index framework and proves the scale invariance of both the Banzhaf and Shapley values within this framework.

It defines:
- `P2a.Game`: A cooperative game with a payoff function.
- `P2a.CohesionStructure`: A structure representing the cohesion of coalitions, which is admissible (every player belongs to some coalition with positive cohesion).
- `P2a.scaleCohesion`: A function to scale a cohesion structure by a positive factor `a`.
- `P2a.FBanzhaf`: The cohesion-sensitive Banzhaf value.
- `P2a.FShapley`: The cohesion-sensitive Shapley value.

It proves:
- `P2a.denomBanzhaf_scale`: The denominator in the Banzhaf calculation scales by `a^b`.
- `P2a.verification_banzhaf_scaleInvariance`: The Banzhaf value is invariant under scaling of the cohesion structure.
- `P2a.denomShapley_scale`: The denominator in the Shapley calculation scales by `a^b`.
- `P2a.verification_shapley_scaleInvariance`: The Shapley value is invariant under scaling of the cohesion structure.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P2a.Player (n : ℕ) := Fin n
def P2a.N (n : ℕ) : Finset (P2a.Player n) := Finset.univ
def P2a.coalitionsWithout (n : ℕ) (i : P2a.Player n) :
    Finset (Finset (P2a.Player n)) :=
  ((P2a.N n).erase i).powerset

structure P2a.Game (n : ℕ) where
  payoff : Finset (P2a.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (P2a.Game n)
    (fun _ => Finset (P2a.Player n) → ℝ) := ⟨P2a.Game.payoff⟩

def P2a.marginalContribution (n : ℕ) (i : P2a.Player n)
    (v : P2a.Game n) (S : Finset (P2a.Player n)) : ℝ :=
  v (insert i S) - v S

structure P2a.CohesionRaw (n : ℕ) where
  coh : Finset (P2a.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P2a.Player n), 0 ≤ coh S
instance (n : ℕ) : CoeFun (P2a.CohesionRaw n)
    (fun _ => Finset (P2a.Player n) → ℝ) := ⟨P2a.CohesionRaw.coh⟩

def P2a.IsAdmissible (n : ℕ) (κ : P2a.CohesionRaw n) : Prop :=
  ∀ i : P2a.Player n, ∃ S : Finset (P2a.Player n), i ∈ S ∧ 0 < κ S

structure P2a.CohesionStructure (n : ℕ) extends P2a.CohesionRaw n where
  admissible' : P2a.IsAdmissible n toCohesionRaw
instance (n : ℕ) : CoeFun (P2a.CohesionStructure n)
    (fun _ => Finset (P2a.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

def P2a.scaleCohesion {n : ℕ} (a : ℝ) (ha : 0 < a)
    (κ : P2a.CohesionStructure n) : P2a.CohesionStructure n :=
  { coh := fun S => a * κ S
    empty' := by simp [κ.toCohesionRaw.empty']
    nonneg' := fun S => mul_nonneg (le_of_lt ha) (κ.toCohesionRaw.nonneg' S)
    admissible' := by
      intro i; obtain ⟨S, hiS, hpos⟩ := κ.admissible' i
      exact ⟨S, hiS, mul_pos ha hpos⟩ }

def P2a.denomBanzhaf (n : ℕ) (b : ℝ) (κ : P2a.CohesionStructure n)
    (i : P2a.Player n) : ℝ :=
  ∑ T ∈ P2a.coalitionsWithout n i, Real.rpow (κ (insert i T)) b

def P2a.pBanzhaf (n : ℕ) (b : ℝ) (κ : P2a.CohesionStructure n)
    (i : P2a.Player n) (S : Finset (P2a.Player n)) : ℝ :=
  Real.rpow (κ (insert i S)) b / P2a.denomBanzhaf n b κ i

def P2a.FBanzhaf (n : ℕ) (b : ℝ) (v : P2a.Game n)
    (κ : P2a.CohesionStructure n) (i : P2a.Player n) : ℝ :=
  ∑ S ∈ P2a.coalitionsWithout n i,
    (P2a.pBanzhaf n b κ i S) * (P2a.marginalContribution n i v S)

def P2a.denomShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2a.CohesionStructure n) (i : P2a.Player n) : ℝ :=
  ∑ T ∈ P2a.coalitionsWithout n i,
    (α T.card) * Real.rpow (κ (insert i T)) b

def P2a.pShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2a.CohesionStructure n) (i : P2a.Player n)
    (S : Finset (P2a.Player n)) : ℝ :=
  (α S.card) * Real.rpow (κ (insert i S)) b / P2a.denomShapley n α b κ i

def P2a.FShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (v : P2a.Game n) (κ : P2a.CohesionStructure n)
    (i : P2a.Player n) : ℝ :=
  ∑ S ∈ P2a.coalitionsWithout n i,
    (P2a.pShapley n α b κ i S) * (P2a.marginalContribution n i v S)

theorem P2a.denomBanzhaf_scale {n : ℕ} {b : ℝ} (hb : 0 < b)
    (κ : P2a.CohesionStructure n) (a : ℝ) (ha : 0 < a) (i : P2a.Player n) :
    P2a.denomBanzhaf n b (P2a.scaleCohesion a ha κ) i =
      Real.rpow a b * P2a.denomBanzhaf n b κ i := by
  -- By definition of $P2a.denomBanzhaf$, we can factor out $a^b$ from the sum.
  simp [P2a.denomBanzhaf, P2a.scaleCohesion];
  -- Apply the property of exponents that $(a * x)^b = a^b * x^b$ to each term in the sum.
  have h_exp : ∀ x ∈ P2a.coalitionsWithout n i, (a * κ.coh (Insert.insert i x)) ^ b = a ^ b * (κ.coh (Insert.insert i x)) ^ b := by
    -- By the properties of exponents, we can split the exponentiation into the product of the exponents.
    intros x hx
    rw [Real.mul_rpow (by positivity) (by
    exact κ.toCohesionRaw.nonneg' _)];
  rw [ Finset.mul_sum _ _ _, Finset.sum_congr rfl h_exp ]

theorem P2a.verification_banzhaf_scaleInvariance
    {n : ℕ} {b : ℝ} (hb : 0 < b) :
    ∀ (v : P2a.Game n) (κ : P2a.CohesionStructure n) (a : ℝ) (ha : 0 < a)
      (i : P2a.Player n),
      P2a.FBanzhaf n b v (P2a.scaleCohesion a ha κ) i =
        P2a.FBanzhaf n b v κ i := by
  intros v κ a ha i; unfold P2a.FBanzhaf; simp +decide [ P2a.pBanzhaf ] ;
  rw [ P2a.denomBanzhaf_scale ];
  · refine Finset.sum_congr rfl fun x hx => ?_;
    unfold P2a.scaleCohesion;
    rw [ Real.mul_rpow ( by positivity ) ( by exact ( κ.toCohesionRaw.nonneg' _ ) ) ] ; ring;
    norm_num [ mul_assoc, mul_comm, mul_left_comm, ne_of_gt ( Real.rpow_pos_of_pos ha b ) ];
  · exact?

theorem P2a.denomShapley_scale {n : ℕ} (α : ℕ → ℝ) {b : ℝ} (hb : 0 < b)
    (κ : P2a.CohesionStructure n) (a : ℝ) (ha : 0 < a) (i : P2a.Player n) :
    P2a.denomShapley n α b (P2a.scaleCohesion a ha κ) i =
      Real.rpow a b * P2a.denomShapley n α b κ i := by
  unfold P2a.denomShapley P2a.scaleCohesion;
  rw [ Finset.mul_sum _ _ _ ] ; refine' Finset.sum_congr rfl fun x hx => _ ; norm_num [ mul_assoc, mul_left_comm, Real.mul_rpow, ha.le ] ;
  exact Or.inl ( Real.mul_rpow ha.le ( by linarith [ κ.toCohesionRaw.nonneg' ( Insert.insert i x ) ] ) )

theorem P2a.verification_shapley_scaleInvariance
    {n : ℕ} (α : ℕ → ℝ) {b : ℝ} (hb : 0 < b) :
    ∀ (v : P2a.Game n) (κ : P2a.CohesionStructure n) (a : ℝ) (ha : 0 < a)
      (i : P2a.Player n),
      P2a.FShapley n α b v (P2a.scaleCohesion a ha κ) i =
        P2a.FShapley n α b v κ i := by
  intro v κ a ha i
  simp [P2a.FShapley, P2a.pShapley, P2a.denomShapley_scale];
  refine' Finset.sum_congr rfl fun x hx => _;
  rw [ show ( P2a.scaleCohesion a ha κ ).coh ( Insert.insert i x ) = a * κ.coh ( Insert.insert i x ) by exact rfl, Real.mul_rpow ( le_of_lt ha ) ( by exact κ.toCohesionRaw.nonneg' _ ) ] ; ring;
  rw [ P2a.denomShapley_scale ] ; ring;
  · simp +decide [ mul_assoc, mul_comm, mul_left_comm, ha.ne', ne_of_gt ( Real.rpow_pos_of_pos ha b ) ];
  · exact?
