/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6ec7c99d-c46f-4e0f-ba8b-6a23bacf9de7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines Cohesion-Sensitive Power Indices (Banzhaf and Shapley) for simple games and proves their cohesion monotonicity.
It defines the game structure, cohesion structure, and the indices.
It includes the helper theorem `P2d.frac_mono_numer` for fraction monotonicity.
It proves `P2d.verification_banzhaf_cohesionMono` and `P2d.verification_shapley_cohesionMono` under the assumption of monotonicity (marginal contributions in {0, 1}).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P2d.Player (n : ℕ) := Fin n
def P2d.N (n : ℕ) : Finset (P2d.Player n) := Finset.univ
def P2d.coalitionsWithout (n : ℕ) (i : P2d.Player n) :
    Finset (Finset (P2d.Player n)) :=
  ((P2d.N n).erase i).powerset

structure P2d.Game (n : ℕ) where
  payoff : Finset (P2d.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (P2d.Game n)
    (fun _ => Finset (P2d.Player n) → ℝ) := ⟨P2d.Game.payoff⟩

def P2d.IsSimpleGame (n : ℕ) (v : P2d.Game n) : Prop :=
  (∀ S : Finset (P2d.Player n), v S = 0 ∨ v S = 1) ∧ v (P2d.N n) = 1

def P2d.marginalContribution (n : ℕ) (i : P2d.Player n)
    (v : P2d.Game n) (S : Finset (P2d.Player n)) : ℝ :=
  v (insert i S) - v S

structure P2d.CohesionRaw (n : ℕ) where
  coh : Finset (P2d.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P2d.Player n), 0 ≤ coh S
instance (n : ℕ) : CoeFun (P2d.CohesionRaw n)
    (fun _ => Finset (P2d.Player n) → ℝ) := ⟨P2d.CohesionRaw.coh⟩

def P2d.IsAdmissible (n : ℕ) (κ : P2d.CohesionRaw n) : Prop :=
  ∀ i : P2d.Player n, ∃ S : Finset (P2d.Player n), i ∈ S ∧ 0 < κ S

structure P2d.CohesionStructure (n : ℕ) extends P2d.CohesionRaw n where
  admissible' : P2d.IsAdmissible n toCohesionRaw
instance (n : ℕ) : CoeFun (P2d.CohesionStructure n)
    (fun _ => Finset (P2d.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

-- Banzhaf
def P2d.denomBanzhaf (n : ℕ) (b : ℝ) (κ : P2d.CohesionStructure n)
    (i : P2d.Player n) : ℝ :=
  ∑ T ∈ P2d.coalitionsWithout n i, Real.rpow (κ (insert i T)) b

def P2d.pBanzhaf (n : ℕ) (b : ℝ) (κ : P2d.CohesionStructure n)
    (i : P2d.Player n) (S : Finset (P2d.Player n)) : ℝ :=
  Real.rpow (κ (insert i S)) b / P2d.denomBanzhaf n b κ i

def P2d.FBanzhaf (n : ℕ) (b : ℝ) (v : P2d.Game n)
    (κ : P2d.CohesionStructure n) (i : P2d.Player n) : ℝ :=
  ∑ S ∈ P2d.coalitionsWithout n i,
    (P2d.pBanzhaf n b κ i S) * (P2d.marginalContribution n i v S)

-- Shapley
def P2d.denomShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2d.CohesionStructure n) (i : P2d.Player n) : ℝ :=
  ∑ T ∈ P2d.coalitionsWithout n i,
    (α T.card) * Real.rpow (κ (insert i T)) b

def P2d.pShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2d.CohesionStructure n) (i : P2d.Player n)
    (S : Finset (P2d.Player n)) : ℝ :=
  (α S.card) * Real.rpow (κ (insert i S)) b / P2d.denomShapley n α b κ i

def P2d.FShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (v : P2d.Game n) (κ : P2d.CohesionStructure n)
    (i : P2d.Player n) : ℝ :=
  ∑ S ∈ P2d.coalitionsWithout n i,
    (P2d.pShapley n α b κ i S) * (P2d.marginalContribution n i v S)

/-- Helper: W_P/(W_P + W_Q) ≤ W'_P/(W'_P + W_Q) when W'_P ≥ W_P ≥ 0, W_Q ≥ 0.
    This is the fraction monotonicity lemma from File 1. -/
theorem P2d.frac_mono_numer
    (W_P W_Q W'_P : ℝ)
    (hWP : 0 ≤ W_P) (hWQ : 0 ≤ W_Q) (hpos : 0 < W_P + W_Q)
    (hge : W_P ≤ W'_P) :
    W_P / (W_P + W_Q) ≤ W'_P / (W'_P + W_Q) := by
  -- By cross-multiplying, we can avoid dealing with fractions.
  have h_cross : W_P * (W'_P + W_Q) ≤ W'_P * (W_P + W_Q) := by
    -- By expanding both sides, we can see that the inequality holds because $W'_P \geq W_P$ and $W_Q \geq 0$.
    nlinarith [mul_le_mul_of_nonneg_left hge hWQ];
  -- By dividing both sides of the inequality $W_P * (W'_P + W_Q) ≤ W'_P * (W_P + W_Q)$ by $(W_P + W_Q) * (W'_P + W_Q)$, we obtain the desired result.
  have h_div : W_P * (W'_P + W_Q) / ((W_P + W_Q) * (W'_P + W_Q)) ≤ W'_P * (W_P + W_Q) / ((W_P + W_Q) * (W'_P + W_Q)) := by
    bound;
  -- By canceling out the common terms in the numerator and denominator, we obtain the desired inequality.
  convert h_div using 1
  field_simp [mul_comm, mul_assoc, mul_left_comm];
  · rw [ mul_div_cancel_right₀ _ ( by linarith ) ];
  · rw [ mul_comm, mul_div_mul_left _ _ hpos.ne' ]

lemma P2d.marginal_in_set {n : ℕ} (v : P2d.Game n) (hv : P2d.IsSimpleGame n v) (i : P2d.Player n) :
    ∀ S, P2d.marginalContribution n i v S ∈ ({-1, 0, 1} : Finset ℝ) := by
  intro S
  unfold P2d.marginalContribution
  have h1 := hv.1 (insert i S)
  have h2 := hv.1 S
  rcases h1 with (h1 | h1) <;> rcases h2 with (h2 | h2)
  · rw [h1, h2]; simp
  · rw [h1, h2]; simp
  · rw [h1, h2]; simp
  · rw [h1, h2]; simp

theorem P2d.verification_banzhaf_cohesionMono
    {n : ℕ} {b : ℝ} (hb : 0 < b) :
    ∀ (v : P2d.Game n) (hv : P2d.IsSimpleGame n v)
      (i : P2d.Player n) (κ κ' : P2d.CohesionStructure n),
    (∀ S ∈ P2d.coalitionsWithout n i, P2d.marginalContribution n i v S = 1 ∨ P2d.marginalContribution n i v S = 0) →
    ((∀ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 1 →
          κ' (insert i S) ≥ κ (insert i S)) ∧
     (∃ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 1 ∧
          κ' (insert i S) > κ (insert i S)) ∧
     (∀ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 0 →
          κ' (insert i S) = κ (insert i S))) →
    P2d.FBanzhaf n b v κ' i ≥ P2d.FBanzhaf n b v κ i := by
      intros v hv i κ κ' h_marginal h_conditions;
      -- Let's define the sets P and Q as described in the provided solution.
      set P := Finset.filter (fun S => P2d.marginalContribution n i v S = 1) (P2d.coalitionsWithout n i)
      set Q := Finset.filter (fun S => P2d.marginalContribution n i v S = 0) (P2d.coalitionsWithout n i);
      -- Show that F(i, v, κ) = WP / (WP + WQ) and F(i, v, κ') = WP' / (WP' + WQ').
      have hF : P2d.FBanzhaf n b v κ i = (∑ S ∈ P, (κ.coh (insert i S)) ^ b) / (∑ S ∈ P, (κ.coh (insert i S)) ^ b + ∑ S ∈ Q, (κ.coh (insert i S)) ^ b) := by
        rw [ Finset.sum_filter, Finset.sum_filter ];
        rw [ ← Finset.sum_add_distrib, Finset.sum_div ];
        refine' Finset.sum_congr rfl fun S hS => _;
        cases h_marginal S hS <;> simp +decide [ *, P2d.pBanzhaf ];
        exact congrArg _ ( Finset.sum_congr rfl fun x hx => by cases h_marginal x hx <;> aesop )
      have hF' : P2d.FBanzhaf n b v κ' i = (∑ S ∈ P, (κ'.coh (insert i S)) ^ b) / (∑ S ∈ P, (κ'.coh (insert i S)) ^ b + ∑ S ∈ Q, (κ'.coh (insert i S)) ^ b) := by
        rw [ Finset.sum_filter, Finset.sum_filter ];
        rw [ ← Finset.sum_add_distrib ];
        rw [ Finset.sum_div _ _ _ ] ; refine' Finset.sum_congr rfl fun x hx => _ ; rcases h_marginal x hx with h | h <;> norm_num [ h ] ;
        exact congrArg _ ( Finset.sum_congr rfl fun y hy => by cases h_marginal y hy <;> aesop );
      -- Show that WP' ≥ WP and WQ' = WQ.
      have hWP : ∑ S ∈ P, (κ'.coh (insert i S)) ^ b ≥ ∑ S ∈ P, (κ.coh (insert i S)) ^ b := by
        exact Finset.sum_le_sum fun x hx => Real.rpow_le_rpow ( by linarith [ show 0 ≤ κ.coh ( Insert.insert i x ) from κ.toCohesionRaw.nonneg' _ ] ) ( h_conditions.1 x ( Finset.filter_subset _ _ hx ) ( Finset.mem_filter.mp hx |>.2 ) ) ( by linarith )
      have hWQ : ∑ S ∈ Q, (κ'.coh (insert i S)) ^ b = ∑ S ∈ Q, (κ.coh (insert i S)) ^ b := by
        exact Finset.sum_congr rfl fun x hx => by rw [ h_conditions.2.2 x ( Finset.mem_filter.mp hx |>.1 ) ( Finset.mem_filter.mp hx |>.2 ) ] ;
      by_cases h : ∑ S ∈ P, κ.coh ( Insert.insert i S ) ^ b = 0 <;> simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, Real.rpow_nonneg ];
      · exact div_nonneg hWP ( add_nonneg hWP ( Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.1.nonneg' _ ) _ ) );
      · rw [ div_le_div_iff₀ ];
        · nlinarith [ show 0 ≤ ∑ S ∈ P, κ.coh ( Insert.insert i S ) ^ b from Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.toCohesionRaw.nonneg' _ ) _, show 0 ≤ ∑ S ∈ Q, κ.coh ( Insert.insert i S ) ^ b from Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.toCohesionRaw.nonneg' _ ) _ ];
        · exact add_pos_of_pos_of_nonneg ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.nonneg' _ ) _ ) ( Ne.symm h ) ) ( Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.nonneg' _ ) _ );
        · exact add_pos_of_pos_of_nonneg ( lt_of_lt_of_le ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.1.nonneg' _ ) _ ) ( Ne.symm h ) ) hWP ) ( Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( κ.1.nonneg' _ ) _ )

theorem P2d.verification_shapley_cohesionMono
    {n : ℕ} (α : ℕ → ℝ) (hα_nonneg : ∀ k, 0 ≤ α k)
    {b : ℝ} (hb : 0 < b) :
    ∀ (v : P2d.Game n) (hv : P2d.IsSimpleGame n v)
      (i : P2d.Player n) (κ κ' : P2d.CohesionStructure n),
    (∀ S ∈ P2d.coalitionsWithout n i, P2d.marginalContribution n i v S = 1 ∨ P2d.marginalContribution n i v S = 0) →
    ((∀ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 1 →
          κ' (insert i S) ≥ κ (insert i S)) ∧
     (∃ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 1 ∧
          κ' (insert i S) > κ (insert i S)) ∧
     (∀ S ∈ P2d.coalitionsWithout n i,
        P2d.marginalContribution n i v S = 0 →
          κ' (insert i S) = κ (insert i S))) →
    P2d.FShapley n α b v κ' i ≥ P2d.FShapley n α b v κ i := by
      intros v hv i κ κ' h₁ h₂;
      -- Let's denote the sum of the weights of coalitions where the marginal contribution is 1 as WP and the sum of the weights of coalitions where the marginal contribution is 0 as WQ.
      set WP := ∑ S ∈ P2d.coalitionsWithout n i, if P2d.marginalContribution n i v S = 1 then (α S.card) * Real.rpow (κ.coh (insert i S)) b else 0
      set WQ := ∑ S ∈ P2d.coalitionsWithout n i, if P2d.marginalContribution n i v S = 0 then (α S.card) * Real.rpow (κ.coh (insert i S)) b else 0
      set WP' := ∑ S ∈ P2d.coalitionsWithout n i, if P2d.marginalContribution n i v S = 1 then (α S.card) * Real.rpow (κ'.coh (insert i S)) b else 0
      set WQ' := ∑ S ∈ P2d.coalitionsWithout n i, if P2d.marginalContribution n i v S = 0 then (α S.card) * Real.rpow (κ'.coh (insert i S)) b else 0;
      -- By definition of $FShapley$, we know that
      have hFShapley : P2d.FShapley n α b v κ i = WP / (WP + WQ) ∧ P2d.FShapley n α b v κ' i = WP' / (WP' + WQ') := by
        simp +decide [ P2d.FShapley, P2d.denomShapley, P2d.pShapley ];
        constructor <;> rw [ Finset.sum_div _ _ _ ];
        · refine' Finset.sum_congr rfl fun x hx => _;
          cases h₁ x hx <;> simp +decide [ * ];
          exact congrArg _ ( by rw [ ← Finset.sum_add_distrib ] ; exact Finset.sum_congr rfl fun y hy => by cases h₁ y hy <;> aesop );
        · refine' Finset.sum_congr rfl fun x hx => _;
          cases h₁ x hx <;> simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ];
          rw [ ← Finset.sum_add_distrib ] ; exact Or.inl <| Or.inl <| Finset.sum_congr rfl fun y hy => by cases h₁ y hy <;> aesop;
      -- By definition of $WP$ and $WP'$, we know that $WP' \geq WP$ and $WQ' = WQ$.
      have hWPWP' : WP' ≥ WP := by
        refine' Finset.sum_le_sum fun S hS => _;
        split_ifs <;> norm_num;
        exact mul_le_mul_of_nonneg_left ( Real.rpow_le_rpow ( by linarith [ κ.toCohesionRaw.nonneg' ( Insert.insert i S ) ] ) ( h₂.1 S hS ‹_› ) hb.le ) ( hα_nonneg _ )
      have hWQWQ' : WQ' = WQ := by
        exact Finset.sum_congr rfl fun x hx => by specialize h₁ x hx; aesop;
      by_cases hWP : WP = 0;
      · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ];
        exact div_nonneg hWPWP' ( add_nonneg hWPWP' ( Finset.sum_nonneg fun _ _ => by split_ifs <;> first | positivity | exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.toCohesionRaw.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ) );
      · rw [ hFShapley.1, hFShapley.2, hWQWQ' ];
        rw [ ge_iff_le, div_le_div_iff₀ ];
        · nlinarith [ show 0 ≤ WP by exact Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ; exact le_rfl ], show 0 ≤ WQ by exact Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ; exact le_rfl ] ];
        · exact add_pos_of_pos_of_nonneg ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => by split_ifs <;> first | positivity | exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.toCohesionRaw.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ) ( Ne.symm hWP ) ) ( Finset.sum_nonneg fun _ _ => by split_ifs <;> first | positivity | exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.toCohesionRaw.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) );
        · exact add_pos_of_pos_of_nonneg ( lt_of_lt_of_le ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.1.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ; exact le_rfl ] ) ( Ne.symm hWP ) ) hWPWP' ) ( Finset.sum_nonneg fun _ _ => by split_ifs <;> [ exact mul_nonneg ( hα_nonneg _ ) ( Real.rpow_nonneg ( by linarith [ κ.1.nonneg' ( Insert.insert i ‹_› ) ] ) _ ) ; exact le_rfl ] )
