/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6fcd6550-020e-4f4f-8452-9f7e125dcd73

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the definitions and the main theorem `P3c.size_kappa_multiplicative` (Lemma A.2) regarding the size-cohesion separability of power indices. The theorem states that if a probability system satisfies size-cohesion separability and symmetry, then the weights ω and exponent b are the same for all players. The proof utilizes the transitive action of the symmetric group on the set of players to show that the player-specific parameters must be identical.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P3c.Player (n : ℕ) := Fin n
def P3c.N (n : ℕ) : Finset (P3c.Player n) := Finset.univ
def P3c.coalitionsWithout (n : ℕ) (i : P3c.Player n) :
    Finset (Finset (P3c.Player n)) :=
  ((P3c.N n).erase i).powerset

structure P3c.CohesionRaw (n : ℕ) where
  coh : Finset (P3c.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P3c.Player n), 0 ≤ coh S

def P3c.IsAdmissible (n : ℕ) (κ : P3c.CohesionRaw n) : Prop :=
  ∀ i : P3c.Player n, ∃ S : Finset (P3c.Player n), i ∈ S ∧ 0 < κ.coh S

structure P3c.CohesionStructure (n : ℕ) extends P3c.CohesionRaw n where
  admissible' : P3c.IsAdmissible n toCohesionRaw

instance (n : ℕ) : CoeFun (P3c.CohesionStructure n)
    (fun _ => Finset (P3c.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

def P3c.permuteCoalition {n : ℕ}
    (perm : Equiv.Perm (P3c.Player n))
    (S : Finset (P3c.Player n)) : Finset (P3c.Player n) :=
  S.map perm.toEmbedding

def P3c.permuteCohesion {n : ℕ}
    (perm : Equiv.Perm (P3c.Player n))
    (κ : P3c.CohesionStructure n) : P3c.CohesionStructure n :=
  { coh := fun S => κ (S.map perm.symm.toEmbedding)
    empty' := by
      -- By definition of $P3c.CohesionStructure$, we know that $κ.coh ∅ = 0$.
      apply κ.toCohesionRaw.empty'
    nonneg' := by
      -- Since κ.coh is non-negative by assumption, applying it to any set, including the image of S under perm.symm, should give a non-negative result.
      intros S
      apply κ.toCohesionRaw.nonneg'
    admissible' := by
      -- For any player $i$, since $\kappa$ is admissible, there exists a coalition $S$ containing $i$ with positive cohesion. Then, taking $T = \text{Finset.map} (\text{Equiv.symm perm}).\text{toEmbedding} S$ gives a coalition in the permuted structure containing $perm i$ with positive cohesion.
      intro i
      obtain ⟨S, hiS, hpos⟩ := κ.admissible' (perm.symm i);
      -- Since $perm$ is a permutation, $perm.symm i$ is just another player. So, if we take $S$ to be the image of $S$ under $perm$, then $i$ should be in $S$ because $perm.symm i$ is in $S$.
      use Finset.map (perm.toEmbedding) S;
      -- Since $perm$ is a permutation, applying it to $S$ gives a set that contains $i$ because $perm.symm i$ is in $S$.
      simp [Finset.mem_map, hiS];
      convert hpos using 1;
      congr! 1;
      ext; simp [Finset.mem_map] }

/-- Probability system with symmetry. -/
structure P3c.ProbSystem (n : ℕ) where
  p : P3c.CohesionStructure n → P3c.Player n → Finset (P3c.Player n) → ℝ

/-- Symmetry axiom for probabilities:
    p_{π(i)}^{πκ}(πS) = pᵢ^κ(S) for all permutations π. -/
def P3c.AxiomProbSymmetry {n : ℕ} (P : P3c.ProbSystem n) : Prop :=
  ∀ (perm : Equiv.Perm (P3c.Player n))
    (κ : P3c.CohesionStructure n) (i : P3c.Player n)
    (S : Finset (P3c.Player n)),
    P.p (P3c.permuteCohesion perm κ) (perm i)
      (P3c.permuteCoalition perm S) = P.p κ i S

/-- Size-cohesion separability axiom (player-specific version):
    For each i, there exist (ωₖ^{(i)}, bᵢ) such that
    p(S) ∝ ωₖ^{(i)} · κ(S∪{i})^{bᵢ}. -/
def P3c.AxiomSizeKappaSeparability {n : ℕ} (P : P3c.ProbSystem n) : Prop :=
  ∀ i : P3c.Player n,
    ∃ (ω : ℕ → ℝ) (b : ℝ),
      (∀ k : ℕ, 0 ≤ ω k) ∧ 0 < b ∧
      ∀ (κ : P3c.CohesionStructure n) (S : Finset (P3c.Player n)),
        S ∈ P3c.coalitionsWithout n i →
          P.p κ i S =
            (ω S.card) * Real.rpow (κ (insert i S)) b /
              (∑ T ∈ P3c.coalitionsWithout n i,
                (ω T.card) * Real.rpow (κ (insert i T)) b)

/-- Lemma A.2: Size-cohesion multiplicative representation.

    If a probability system satisfies size-cohesion separability
    (player-specific) and symmetry, then the weights ω and exponent b
    are the same for all players.

    PROOF:
    For each i we have (ωᵢ, bᵢ). By symmetry:
      p_{π(i)}^{πκ}(πS) = pᵢ^κ(S).
    The LHS uses (ω_{π(i)}, b_{π(i)}) and the RHS uses (ωᵢ, bᵢ).
    Since |πS| = |S| and πκ(insert π(i) πS) = κ(insert i S),
    the uniqueness of the representation forces
      ω_{π(i)} = ωᵢ and b_{π(i)} = bᵢ.
    The symmetric group acts transitively on Fin n (for n ≥ 1),
    so all (ωᵢ, bᵢ) are identical. -/
theorem P3c.size_kappa_multiplicative
    {n : ℕ} (P : P3c.ProbSystem n)
    (hSep : P3c.AxiomSizeKappaSeparability P)
    (hSym : P3c.AxiomProbSymmetry P) :
    ∃ (ω : ℕ → ℝ) (b : ℝ),
      (∀ k : ℕ, 0 ≤ ω k) ∧ 0 < b ∧
      ∀ (κ : P3c.CohesionStructure n) (i : P3c.Player n)
        (S : Finset (P3c.Player n)),
        S ∈ P3c.coalitionsWithout n i →
          P.p κ i S =
            ((ω S.card) * Real.rpow (κ (insert i S)) b) /
              (∑ T ∈ P3c.coalitionsWithout n i,
                (ω T.card) * Real.rpow (κ (insert i T)) b) := by
  obtain ⟨ω₁, b₁, hω₁_nonneg, hb₁_pos, hω₁⟩ : ∃ ω₁ : ℕ → ℝ, ∃ b₁ : ℝ, (∀ k : ℕ, 0 ≤ ω₁ k) ∧ 0 < b₁ ∧ ∀ κ : P3c.CohesionStructure n, ∀ i : P3c.Player n, ∀ S ∈ P3c.coalitionsWithout n i, P.p κ i S = (ω₁ S.card) * Real.rpow (κ (insert i S)) b₁ / (∑ T ∈ P3c.coalitionsWithout n i, (ω₁ T.card) * Real.rpow (κ (insert i T)) b₁) := by
    have := hSep
    rcases n with ( _ | n ) <;> simp_all +decide [ P3c.N ];
    · exact ⟨ ⟨ fun _ => 0, fun _ => by norm_num ⟩, 1, by norm_num ⟩;
    · obtain ⟨ ω₁, b₁, hω₁_nonneg, hb₁_pos, hω₁ ⟩ := this 0;
      refine' ⟨ ω₁, hω₁_nonneg, b₁, hb₁_pos, fun κ i S hi => _ ⟩;
      -- By symmetry, we can assume without loss of generality that $i = 0$.
      obtain ⟨perm, hperm⟩ : ∃ perm : Equiv.Perm (P3c.Player (n + 1)), perm i = 0 := by
        exact ⟨ Equiv.swap i 0, by simp +decide ⟩;
      have := hSym perm κ i S; simp_all +decide [ P3c.permuteCoalition, P3c.permuteCohesion ] ;
      rw [ ← this, hω₁ ];
      · rw [ show P3c.coalitionsWithout ( n + 1 ) 0 = Finset.image ( fun x => Finset.map ( Equiv.toEmbedding perm ) x ) ( P3c.coalitionsWithout ( n + 1 ) i ) from ?_, Finset.sum_image ] <;> norm_num [ Finset.card_image_of_injective, Function.Injective ];
        · simp +decide [ ← hperm, Equiv.symm_apply_apply ];
          simp +decide [ Finset.map_map, Equiv.symm_apply_apply ];
        · ext; simp [P3c.coalitionsWithout];
          constructor <;> intro h <;> simp_all +decide [ Finset.subset_iff, P3c.N ];
          · use Finset.image (fun x => perm.symm x) ‹_›; simp_all +decide [ Finset.ext_iff, Equiv.symm_apply_eq ] ;
          · rcases h with ⟨ a, ha₁, rfl ⟩ ; simp +decide [ ← hperm, ha₁ ] ;
      · simp_all +decide [ P3c.coalitionsWithout ];
        simp_all +decide [ Finset.subset_iff, P3c.N ];
        grind;
  use ω₁, b₁
