/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7d66836b-506f-474b-954c-6d02f0ee6c0b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines Cohesion-Sensitive Power Indices (Banzhaf and Shapley variants) and proves that in a dictator game, the dictator's value is 1.
It includes definitions for `P2c.Game`, `P2c.CohesionStructure`, and the Banzhaf and Shapley indices (`P2c.FBanzhaf`, `P2c.FShapley`).
The main results are `P2c.dictator_banzhaf_value_one` and `P2c.dictator_shapley_value_one`, which establish that the dictator's power index is 1 in both cases.
Helper lemmas `P2c.dictator_marginal_one`, `P2c.mem_coalitionsWithout_not_mem`, `P2c.banzhaf_prob_sum_one`, and `P2c.shapley_prob_sum_one` are also proved.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P2c.Player (n : ℕ) := Fin n
def P2c.N (n : ℕ) : Finset (P2c.Player n) := Finset.univ
def P2c.coalitionsWithout (n : ℕ) (i : P2c.Player n) :
    Finset (Finset (P2c.Player n)) :=
  ((P2c.N n).erase i).powerset

structure P2c.Game (n : ℕ) where
  payoff : Finset (P2c.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (P2c.Game n)
    (fun _ => Finset (P2c.Player n) → ℝ) := ⟨P2c.Game.payoff⟩

def P2c.marginalContribution (n : ℕ) (i : P2c.Player n)
    (v : P2c.Game n) (S : Finset (P2c.Player n)) : ℝ :=
  v (insert i S) - v S

structure P2c.CohesionRaw (n : ℕ) where
  coh : Finset (P2c.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P2c.Player n), 0 ≤ coh S
instance (n : ℕ) : CoeFun (P2c.CohesionRaw n)
    (fun _ => Finset (P2c.Player n) → ℝ) := ⟨P2c.CohesionRaw.coh⟩

def P2c.IsAdmissible (n : ℕ) (κ : P2c.CohesionRaw n) : Prop :=
  ∀ i : P2c.Player n, ∃ S : Finset (P2c.Player n), i ∈ S ∧ 0 < κ S

structure P2c.CohesionStructure (n : ℕ) extends P2c.CohesionRaw n where
  admissible' : P2c.IsAdmissible n toCohesionRaw
instance (n : ℕ) : CoeFun (P2c.CohesionStructure n)
    (fun _ => Finset (P2c.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

def P2c.dictatorGame (n : ℕ) (d : P2c.Player n) : P2c.Game n :=
  { payoff := fun S => if d ∈ S then 1 else 0, empty' := by simp }

-- Banzhaf
def P2c.denomBanzhaf (n : ℕ) (b : ℝ) (κ : P2c.CohesionStructure n)
    (i : P2c.Player n) : ℝ :=
  ∑ T ∈ P2c.coalitionsWithout n i, Real.rpow (κ (insert i T)) b

def P2c.pBanzhaf (n : ℕ) (b : ℝ) (κ : P2c.CohesionStructure n)
    (i : P2c.Player n) (S : Finset (P2c.Player n)) : ℝ :=
  Real.rpow (κ (insert i S)) b / P2c.denomBanzhaf n b κ i

def P2c.FBanzhaf (n : ℕ) (b : ℝ) (v : P2c.Game n)
    (κ : P2c.CohesionStructure n) (i : P2c.Player n) : ℝ :=
  ∑ S ∈ P2c.coalitionsWithout n i,
    (P2c.pBanzhaf n b κ i S) * (P2c.marginalContribution n i v S)

-- Shapley
def P2c.denomShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2c.CohesionStructure n) (i : P2c.Player n) : ℝ :=
  ∑ T ∈ P2c.coalitionsWithout n i,
    (α T.card) * Real.rpow (κ (insert i T)) b

def P2c.pShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2c.CohesionStructure n) (i : P2c.Player n)
    (S : Finset (P2c.Player n)) : ℝ :=
  (α S.card) * Real.rpow (κ (insert i S)) b / P2c.denomShapley n α b κ i

def P2c.FShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (v : P2c.Game n) (κ : P2c.CohesionStructure n)
    (i : P2c.Player n) : ℝ :=
  ∑ S ∈ P2c.coalitionsWithout n i,
    (P2c.pShapley n α b κ i S) * (P2c.marginalContribution n i v S)

/-
In the dictator game, the marginal contribution of the dictator d to any coalition S not containing d is 1.
-/
/-- Helper: In the dictator game, Δ_d v(S) = 1 for all S with d ∉ S.
    (d ∉ S implies d ∈ insert d S and d ∉ S, so v(insert d S) - v(S) = 1 - 0 = 1.) -/
theorem P2c.dictator_marginal_one
    {n : ℕ} (d : P2c.Player n) :
    ∀ S : Finset (P2c.Player n), d ∉ S →
      P2c.marginalContribution n d (P2c.dictatorGame n d) S = 1 := by
  unfold P2c.marginalContribution P2c.dictatorGame; aesop;

/-
If S is in coalitionsWithout i, then i is not in S.
-/
/-- Helper: All S in coalitionsWithout(d) satisfy d ∉ S. -/
theorem P2c.mem_coalitionsWithout_not_mem
    {n : ℕ} (i : P2c.Player n) (S : Finset (P2c.Player n))
    (hS : S ∈ P2c.coalitionsWithout n i) : i ∉ S := by
  exact fun hi => Finset.notMem_erase _ _ ( Finset.mem_powerset.mp hS hi )

/-
The sum of Banzhaf probabilities over all coalitions without i is 1.
-/
/-- Helper (Banzhaf): Probabilities sum to 1.
    ∑_S p(S) = ∑_S κ^b/D = D/D = 1. -/
theorem P2c.banzhaf_prob_sum_one
    {n : ℕ} {b : ℝ} (hb : 0 < b) (i : P2c.Player n)
    (κ : P2c.CohesionStructure n)
    (hden : 0 < P2c.denomBanzhaf n b κ i) :
    ∑ S ∈ P2c.coalitionsWithout n i, P2c.pBanzhaf n b κ i S = 1 := by
  -- Since these are probabilities, their sum over all possible events must be 1.
  have h_prob_sum : ∑ x ∈ P2c.coalitionsWithout n i, Real.rpow (κ (insert i x)) b = P2c.denomBanzhaf n b κ i := by
    rfl;
  convert congr_arg ( fun x : ℝ => x / P2c.denomBanzhaf n b κ i ) h_prob_sum using 1 <;> norm_num [ Finset.sum_div _ _ _, hden.ne' ];
  exact Finset.sum_congr rfl fun _ _ => rfl

/-
The sum of Shapley probabilities over all coalitions without i is 1.
-/
/-- Helper (Shapley): Probabilities sum to 1.
    ∑_S p(S) = ∑_S α·κ^b/D = D/D = 1. -/
theorem P2c.shapley_prob_sum_one
    {n : ℕ} (α : ℕ → ℝ) {b : ℝ} (hb : 0 < b) (i : P2c.Player n)
    (κ : P2c.CohesionStructure n)
    (hden : 0 < P2c.denomShapley n α b κ i) :
    ∑ S ∈ P2c.coalitionsWithout n i, P2c.pShapley n α b κ i S = 1 := by
  simp +decide [ P2c.pShapley ];
  rw [ ← Finset.sum_div, div_eq_iff ] <;> aesop

/-
The Banzhaf value of a dictator is 1.
-/
/-- Dictator gets Banzhaf value 1.
    F_d = ∑_S p_d^κ(S) · Δ_d v(S)
        = ∑_S p_d^κ(S) · 1    (since Δ_d v(S) = 1 for all S with d ∉ S)
        = ∑_S p_d^κ(S)
        = 1                    (probabilities sum to 1). -/
theorem P2c.dictator_banzhaf_value_one
    {n : ℕ} {b : ℝ} (hb : 0 < b) (d : P2c.Player n)
    (κ : P2c.CohesionStructure n)
    (hden : 0 < P2c.denomBanzhaf n b κ d) :
    P2c.FBanzhaf n b (P2c.dictatorGame n d) κ d = 1 := by
  -- By definition of $FBanzhaf$, we have:
  simp [P2c.FBanzhaf];
  convert P2c.banzhaf_prob_sum_one hb d κ hden using 2;
  rw [ P2c.dictator_marginal_one _ _ ] ; norm_num;
  exact?

/-
The Shapley value of a dictator is 1.
-/
/-- Dictator gets Shapley value 1. Same argument. -/
theorem P2c.dictator_shapley_value_one
    {n : ℕ} (α : ℕ → ℝ) {b : ℝ} (hb : 0 < b) (d : P2c.Player n)
    (κ : P2c.CohesionStructure n)
    (hden : 0 < P2c.denomShapley n α b κ d) :
    P2c.FShapley n α b (P2c.dictatorGame n d) κ d = 1 := by
  -- By definition of/controller, the denominator and probabilities sum to 1.
  have hsum_prob : ∑ S ∈ P2c.coalitionsWithout n d, P2c.pShapley n α b κ d S = 1 := by
    exact?;
  convert hsum_prob using 1;
  refine' Finset.sum_congr rfl _;
  intro S hS; rw [ show P2c.marginalContribution n d ( P2c.dictatorGame n d ) S = 1 from ?_ ] ; ring;
  exact P2c.dictator_marginal_one d S ( P2c.mem_coalitionsWithout_not_mem d S hS )
