/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d0130781-7f3f-4a7e-8168-26c63bd0093d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This file defines the cohesionless benchmark (κ = 1) for Cohesion-Sensitive Power Indices and verifies that the Banzhaf and Shapley indices reduce to their standard forms (uniform and size-weighted, respectively) in this case. All theorems have been formally proven.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise


abbrev P2b.Player (n : ℕ) := Fin n
def P2b.N (n : ℕ) : Finset (P2b.Player n) := Finset.univ
def P2b.coalitionsWithout (n : ℕ) (i : P2b.Player n) :
    Finset (Finset (P2b.Player n)) :=
  ((P2b.N n).erase i).powerset

structure P2b.Game (n : ℕ) where
  payoff : Finset (P2b.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (P2b.Game n)
    (fun _ => Finset (P2b.Player n) → ℝ) := ⟨P2b.Game.payoff⟩

def P2b.marginalContribution (n : ℕ) (i : P2b.Player n)
    (v : P2b.Game n) (S : Finset (P2b.Player n)) : ℝ :=
  v (insert i S) - v S

structure P2b.CohesionRaw (n : ℕ) where
  coh : Finset (P2b.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P2b.Player n), 0 ≤ coh S
instance (n : ℕ) : CoeFun (P2b.CohesionRaw n)
    (fun _ => Finset (P2b.Player n) → ℝ) := ⟨P2b.CohesionRaw.coh⟩

def P2b.IsAdmissible (n : ℕ) (κ : P2b.CohesionRaw n) : Prop :=
  ∀ i : P2b.Player n, ∃ S : Finset (P2b.Player n), i ∈ S ∧ 0 < κ S

structure P2b.CohesionStructure (n : ℕ) extends P2b.CohesionRaw n where
  admissible' : P2b.IsAdmissible n toCohesionRaw
instance (n : ℕ) : CoeFun (P2b.CohesionStructure n)
    (fun _ => Finset (P2b.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

def P2b.kappaOne (n : ℕ) : P2b.CohesionStructure n :=
  { coh := fun S => if S = ∅ then (0 : ℝ) else 1
    empty' := by simp
    nonneg' := by intro S; by_cases h : S = ∅ <;> simp [h]
    admissible' := by
      intro i; exact ⟨{i}, by simp, by simp [show ({i} : Finset (P2b.Player n)) ≠ ∅ from by simp]⟩ }

-- Banzhaf
def P2b.denomBanzhaf (n : ℕ) (b : ℝ) (κ : P2b.CohesionStructure n)
    (i : P2b.Player n) : ℝ :=
  ∑ T ∈ P2b.coalitionsWithout n i, Real.rpow (κ (insert i T)) b

def P2b.pBanzhaf (n : ℕ) (b : ℝ) (κ : P2b.CohesionStructure n)
    (i : P2b.Player n) (S : Finset (P2b.Player n)) : ℝ :=
  Real.rpow (κ (insert i S)) b / P2b.denomBanzhaf n b κ i

-- Shapley
def P2b.denomShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2b.CohesionStructure n) (i : P2b.Player n) : ℝ :=
  ∑ T ∈ P2b.coalitionsWithout n i,
    (α T.card) * Real.rpow (κ (insert i T)) b

def P2b.pShapley (n : ℕ) (α : ℕ → ℝ) (b : ℝ)
    (κ : P2b.CohesionStructure n) (i : P2b.Player n)
    (S : Finset (P2b.Player n)) : ℝ :=
  (α S.card) * Real.rpow (κ (insert i S)) b / P2b.denomShapley n α b κ i

/-- Helper: For any S ∈ coalitionsWithout(i), insert i S is nonempty,
    so κ₁(insert i S) = 1. -/
theorem P2b.kappaOne_insert {n : ℕ} (i : P2b.Player n)
    (S : Finset (P2b.Player n)) (hS : S ∈ P2b.coalitionsWithout n i) :
    (P2b.kappaOne n) (insert i S) = 1 := by
  -- Since $S$ is a coalition without $i$, $insert i S$ is not empty, hence $\kappa(Insert.insert i S) = 1$.
  simp [P2b.kappaOne]

/-- Helper: 1^b = 1 for any b (using Real.rpow). -/
theorem P2b.one_rpow_eq (b : ℝ) : Real.rpow 1 b = 1 := by
  -- By definition of exponentiation, we know that $1^b = 1$ for any real number $b$.
  simp [Real.rpow_one]

/-- Helper: The Banzhaf denominator at κ=1 equals the number of coalitions
    not containing i, which is 2^{n-1}.
    denomBanzhaf(1) = ∑_T 1^b = |coalitionsWithout(i)| = 2^{n-1}. -/
theorem P2b.denomBanzhaf_kappaOne {n : ℕ} {b : ℝ} (hb : 0 < b)
    (i : P2b.Player n) :
    P2b.denomBanzhaf n b (P2b.kappaOne n) i =
      (P2b.coalitionsWithout n i).card := by
  -- Since κ₁(insert i T) = 1 for any T in coalitionsWithout(i), each term in the sum is (1 : ℝ) ^ b = 1.
  have h_term : ∀ T ∈ P2b.coalitionsWithout n i, Real.rpow (P2b.kappaOne n (insert i T)) b = 1 := by
    -- Since κ₁(insert i T) = 1 for any T in coalitionsWithout(i), we have (1 : ℝ) ^ b = 1.
    intros T hT
    have h_kappa : (P2b.kappaOne n) (insert i T) = 1 := by
      -- Since κ₁ is defined as 1 for any non-empty set, we have κ₁(insert i T) = 1.
      apply P2b.kappaOne_insert i T hT
    rw [h_kappa]
    simp [Real.rpow_one];
  convert Finset.sum_congr rfl h_term using 1 ; norm_num [ P2b.denomBanzhaf ]

/-- Lemma A.3(7): At κ = 1, Banzhaf probabilities are uniform: 1/2^{n-1}.
    Since κ₁(S∪{i}) = 1 for all S, we get 1^b = 1, so
    p(S) = 1 / |coalitionsWithout(i)| = 1 / 2^{n-1}. -/
theorem P2b.verification_banzhaf_uniform
    {n : ℕ} {b : ℝ} (hb : 0 < b) :
    ∀ (i : P2b.Player n) (S : Finset (P2b.Player n)),
      S ∈ P2b.coalitionsWithout n i →
        P2b.pBanzhaf n b (P2b.kappaOne n) i S =
          (1 : ℝ) / ((2 : ℝ) ^ (n - 1)) := by
  -- Substitute the values we've established for κ₁ and the denominator.
  intro i S hS
  simp [P2b.pBanzhaf, P2b.kappaOne_insert, P2b.denomBanzhaf_kappaOne];
  rw [ P2b.denomBanzhaf_kappaOne hb i ];
  -- Since there are $2^{n-1}$ subsets of a set with $n$ elements, we have $(P2b.coalitionsWithout n i).card = 2^{n-1}$.
  have h_card : (P2b.coalitionsWithout n i).card = 2 ^ (n - 1) := by
    unfold P2b.coalitionsWithout;
    unfold P2b.N; aesop;
  rw [ h_card, P2b.kappaOne_insert i S hS ] ; norm_num

/-- Helper: The Shapley denominator at κ=1 equals ∑ C(n-1,k) α_k = 1
    (by the normalization condition on α). -/
theorem P2b.denomShapley_kappaOne {n : ℕ} (α : ℕ → ℝ)
    (hα_nonneg : ∀ k, 0 ≤ α k)
    (hα_norm : (∑ k ∈ Finset.range n, ((Nat.choose (n - 1) k : ℝ) * α k)) = 1)
    {b : ℝ} (hb : 0 < b) (i : P2b.Player n) :
    P2b.denomShapley n α b (P2b.kappaOne n) i = 1 := by
  convert hα_norm using 1;
  -- The sum over all coalitions S not containing i, of α(S.card), is equal to the sum over k from 0 to n-1, of (n-1 choose k) * α(k), because each coalition S corresponds to a subset of size k, and there are (n-1 choose k) such subsets.
  have h_sum_eq : ∑ S ∈ P2b.coalitionsWithout n i, α S.card = ∑ k ∈ Finset.range n, (Nat.choose (n - 1) k) * α k := by
    -- The sum over all subsets S of N \ {i} can be reorganized by grouping subsets of the same size.
    have h_group : ∑ S ∈ Finset.powerset (Finset.univ.erase i), α S.card = ∑ k ∈ Finset.range n, ∑ S ∈ Finset.powersetCard k (Finset.univ.erase i), α S.card := by
      rw [ Finset.sum_powerset ];
      cases n <;> aesop;
    simp_all +decide [ Finset.sum_powersetCard ];
    exact h_group;
  convert h_sum_eq using 1;
  refine' Finset.sum_congr rfl fun S hS => _;
  unfold P2b.kappaOne; aesop;

/-- Lemma A.4(7): At κ = 1, Shapley probabilities equal size weights α_{|S|}.
    Since κ₁^b = 1 and denomShapley(1) = 1 (by normalization),
    p(S) = α_{|S|} · 1 / 1 = α_{|S|}. -/
theorem P2b.verification_shapley_benchmark
    {n : ℕ} (α : ℕ → ℝ) (hα_nonneg : ∀ k, 0 ≤ α k)
    (hα_norm : (∑ k ∈ Finset.range n, ((Nat.choose (n - 1) k : ℝ) * α k)) = 1)
    {b : ℝ} (hb : 0 < b) :
    ∀ (i : P2b.Player n) (S : Finset (P2b.Player n)),
      S ∈ P2b.coalitionsWithout n i →
        P2b.pShapley n α b (P2b.kappaOne n) i S = α S.card := by
  -- Since the denominator is 1 and 1^b is 1, the expression simplifies to α(S.card).
  intros i S hS
  simp [P2b.pShapley, P2b.denomShapley_kappaOne α hα_nonneg hα_norm hb i];
  -- Since κ₁(insert i S) = 1 for any S in coalitionsWithout(i), we have (P2b.kappaOne n).coh (insert i S) = 1.
  have h_kappa_one : (P2b.kappaOne n).coh (insert i S) = 1 := by
    -- Since κ₁ is defined as 1 for all non-empty sets, we have κ₁(insert i S) = 1.
    apply P2b.kappaOne_insert i S hS;
  -- Since $1^b = 1$ for any $b$, we can simplify the expression.
  simp [h_kappa_one, Real.rpow_one]
