/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d9cc39a7-8e2d-458c-aff0-01604a3e77f5

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We formalized the definitions of Cohesion-Sensitive Power Indices and the Luce Representation Lemma. We found that the original statement of Lemma A.1 (`P3b.luce_representation`) is false as stated because it lacks a "faithfulness" assumption (zero cohesion implies zero probability). We proved a corrected version `P3b.luce_representation_corrected` that includes this assumption. We also formally proved `P3b.counterexample_to_luce_proof`, showing that there exists a probability system satisfying the regularity axiom but failing the representation formula for unfaithful structures.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P3b.Player (n : ℕ) := Fin n

def P3b.N (n : ℕ) : Finset (P3b.Player n) := Finset.univ

def P3b.coalitionsWithout (n : ℕ) (i : P3b.Player n) :
    Finset (Finset (P3b.Player n)) :=
  ((P3b.N n).erase i).powerset

structure P3b.CohesionRaw (n : ℕ) where
  coh : Finset (P3b.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P3b.Player n), 0 ≤ coh S

def P3b.IsAdmissible (n : ℕ) (κ : P3b.CohesionRaw n) : Prop :=
  ∀ i : P3b.Player n, ∃ S : Finset (P3b.Player n), i ∈ S ∧ 0 < κ.coh S

structure P3b.CohesionStructure (n : ℕ) extends P3b.CohesionRaw n where
  admissible' : P3b.IsAdmissible n toCohesionRaw

instance (n : ℕ) : CoeFun (P3b.CohesionStructure n)
    (fun _ => Finset (P3b.Player n) → ℝ) := ⟨fun κ => κ.toCohesionRaw.coh⟩

/-- Probability system: assigns to each (κ, i, S) a probability p_i^κ(S). -/
structure P3b.ProbSystem (n : ℕ) where
  p : P3b.CohesionStructure n → P3b.Player n → Finset (P3b.Player n) → ℝ

/-- The Luce-type regularity axiom (Banzhaf branch):
    For each player i, there exists b > 0 such that
    p_i^κ(S) ∝ κ(S∪{i})^b, with probabilities summing to 1. -/
def P3b.AxiomCohesionRegularity {n : ℕ} (P : P3b.ProbSystem n) : Prop :=
  ∀ i : P3b.Player n,
    ∃ b : ℝ, 0 < b ∧
      ∀ κ : P3b.CohesionStructure n,
        -- probabilities are proportional to κ(S∪{i})^b
        (∀ S T : Finset (P3b.Player n),
          S ∈ P3b.coalitionsWithout n i →
          T ∈ P3b.coalitionsWithout n i →
          κ (insert i T) > 0 →
          P.p κ i T > 0 →
            P.p κ i S / P.p κ i T =
              Real.rpow (κ (insert i S)) b / Real.rpow (κ (insert i T)) b) ∧
        -- probabilities sum to 1
        (∑ S ∈ P3b.coalitionsWithout n i, P.p κ i S = 1) ∧
        -- probabilities are non-negative
        (∀ S ∈ P3b.coalitionsWithout n i, 0 ≤ P.p κ i S)

/-
A probability system is faithful if zero cohesion implies zero probability.
-/
def P3b.Faithful {n : ℕ} (P : P3b.ProbSystem n) : Prop :=
  ∀ i : P3b.Player n, ∀ κ : P3b.CohesionStructure n, ∀ S : Finset (P3b.Player n),
    S ∈ P3b.coalitionsWithout n i → κ (insert i S) = 0 → P.p κ i S = 0

theorem P3b.luce_representation_corrected
    {n : ℕ} (P : P3b.ProbSystem n)
    (hReg : P3b.AxiomCohesionRegularity P)
    (hFaith : P3b.Faithful P) :
    ∀ i : P3b.Player n, ∃ b : ℝ, 0 < b ∧
      ∀ (κ : P3b.CohesionStructure n) (S : Finset (P3b.Player n)),
        S ∈ P3b.coalitionsWithout n i →
          P.p κ i S =
            Real.rpow (κ (insert i S)) b /
              (∑ T ∈ P3b.coalitionsWithout n i,
                Real.rpow (κ (insert i T)) b) := by
                  intro i
                  obtain ⟨b, hb_pos, hb⟩ := hReg i;
                  use b, hb_pos;
                  intro κ S hS
                  by_cases hκ_pos : ∃ T ∈ P3b.coalitionsWithout n i, κ.coh (insert i T) > 0 ∧ P.p κ i T > 0;
                  · obtain ⟨ T, hT₁, hT₂, hT₃ ⟩ := hκ_pos
                    have h_cross_product : ∀ U ∈ P3b.coalitionsWithout n i, P.p κ i U * (κ.coh (insert i T)).rpow b = P.p κ i T * (κ.coh (insert i U)).rpow b := by
                      grind;
                    have h_sum_cross_product : ∑ U ∈ P3b.coalitionsWithout n i, P.p κ i U * (κ.coh (insert i T)).rpow b = P.p κ i T * ∑ U ∈ P3b.coalitionsWithout n i, (κ.coh (insert i U)).rpow b := by
                      rw [ Finset.mul_sum _ _ _, Finset.sum_congr rfl h_cross_product ];
                    rw [ ← Finset.sum_mul _ _ _, hb κ |>.2.1 ] at h_sum_cross_product;
                    grind;
                  · have h_zero : ∀ T ∈ P3b.coalitionsWithout n i, P.p κ i T = 0 := by
                      intro T hT;
                      contrapose! hκ_pos;
                      exact ⟨ T, hT, lt_of_le_of_ne ( by exact κ.toCohesionRaw.nonneg' _ ) ( Ne.symm <| by specialize hFaith i κ T hT; aesop ), lt_of_le_of_ne ( hb κ |>.2.2 T hT ) ( Ne.symm hκ_pos ) ⟩;
                    specialize hb κ; aesop;

/-
A specific probability system for the counterexample.
-/
def P3b.counterexample_P : P3b.ProbSystem 2 :=
  {
    p := fun κ i S =>
      if i = 0 then
        if κ (insert 0 {1}) = 0 then
          if S = {1} then 1 else 0
        else
          let Z := ∑ T ∈ P3b.coalitionsWithout 2 0, Real.rpow (κ (insert 0 T)) 1
          if Z = 0 then (if S = {1} then 1 else 0) -- Fallback
          else Real.rpow (κ (insert 0 S)) 1 / Z
      else
        let Z := ∑ T ∈ P3b.coalitionsWithout 2 i, Real.rpow (κ (insert i T)) 1
        if Z = 0 then (if S = {0} then 1 else 0) -- Fallback
        else Real.rpow (κ (insert i S)) 1 / Z
  }

/-
A specific cohesion structure for the counterexample.
-/
def P3b.counterexample_kappa : P3b.CohesionStructure 2 :=
  {
    coh := fun S => if S = {0} ∨ S = {1} then 1 else 0
    empty' := by
      simp
      push_neg
      constructor
      · exact (Finset.singleton_ne_empty 0).symm
      · exact (Finset.singleton_ne_empty 1).symm
    nonneg' := by intro S; split_ifs <;> norm_num
    admissible' := by
      intro i
      fin_cases i
      · use {0}; simp
      · use {1}; simp
  }

theorem P3b.counterexample_to_luce :
    ∃ (n : ℕ) (P : P3b.ProbSystem n),
      P3b.AxiomCohesionRegularity P ∧
      ¬ (∀ i : P3b.Player n, ∃ b : ℝ, 0 < b ∧
        ∀ (κ : P3b.CohesionStructure n) (S : Finset (P3b.Player n)),
          S ∈ P3b.coalitionsWithout n i →
            P.p κ i S =
              Real.rpow (κ (insert i S)) b /
                (∑ T ∈ P3b.coalitionsWithout n i,
                  Real.rpow (κ (insert i T)) b)) := by
                    use 2, P3b.counterexample_P;
                    constructor;
                    · intro i
                      use 1
                      simp [P3b.counterexample_P];
                      fin_cases i <;> simp +decide [ P3b.coalitionsWithout ];
                      · intro κ; split_ifs <;> simp_all +decide [ Finset.sum_div _ _ _ ] ;
                        · aesop;
                        · rename_i h₁ h₂;
                          contrapose! h₂;
                          refine' ne_of_gt ( lt_of_lt_of_le _ ( Finset.single_le_sum ( fun x _ => _ ) ( show { 1 } ∈ _ from _ ) ) ) <;> norm_num;
                          · exact lt_of_le_of_ne ( κ.nonneg' _ ) ( Ne.symm h₁ );
                          · exact κ.nonneg' _;
                          · exact Finset.mem_univ _;
                        · simp_all +decide [ Finset.sum_div _ _ _, div_div_div_cancel_right₀ ];
                          exact ⟨ by rw [ ← Finset.sum_div _ _ _, div_self ‹_› ], fun S hS => div_nonneg ( by exact κ.nonneg' _ ) ( Finset.sum_nonneg fun _ _ => by exact κ.nonneg' _ ) ⟩;
                      · intro κ; constructor;
                        · intro S T hS hT h₁ h₂; split_ifs at * <;> simp_all +decide [ ne_of_gt, div_eq_mul_inv ] ;
                          · rename_i h₂ h₃ h₄;
                            contrapose! h₂;
                            refine' ne_of_gt ( lt_of_lt_of_le _ ( Finset.single_le_sum ( fun x _ => _ ) ( Finset.mem_powerset.mpr hS ) ) );
                            · exact lt_of_le_of_ne ( κ.nonneg' _ ) ( Ne.symm h₂ );
                            · exact κ.nonneg' _;
                          · rw [ mul_assoc, inv_mul_cancel_left₀ h₂.ne' ];
                        · constructor;
                          · exact fun h => by rw [ ← Finset.sum_div, div_self h ] ;
                          · intro S hS; split_ifs <;> norm_num;
                            exact div_nonneg ( by exact κ.nonneg' _ ) ( Finset.sum_nonneg fun _ _ => by exact κ.nonneg' _ );
                    · push_neg;
                      refine' ⟨ 0, fun x hx => ⟨ P3b.counterexample_kappa, { 1 }, _, _ ⟩ ⟩ <;> norm_num [ P3b.coalitionsWithout ];
                      · exact Finset.mem_univ _;
                      · unfold P3b.counterexample_P P3b.counterexample_kappa; norm_num [ hx.ne' ] ;
                        simp +decide [ Finset.ext_iff ]

#check P3b.counterexample_kappa

/-
The counterexample probability system satisfies the regularity axiom.
-/
lemma P3b.counterexample_P_is_regular :
    P3b.AxiomCohesionRegularity (P3b.counterexample_P) := by
      intro i
      use 1
      simp [P3b.counterexample_P];
      fin_cases i <;> simp +decide [ P3b.coalitionsWithout ];
      · intro κ; split_ifs <;> simp_all +decide [ Finset.sum_div _ _ _ ] ;
        · aesop;
        · rename_i h₁ h₂;
          contrapose! h₂;
          refine' ne_of_gt ( lt_of_lt_of_le _ ( Finset.single_le_sum ( fun x _ => _ ) ( Finset.mem_powerset.mpr ( Finset.singleton_subset_iff.mpr ( Finset.mem_erase_of_ne_of_mem ( by decide ) ( Finset.mem_univ 1 ) ) ) ) ) );
          · exact lt_of_le_of_ne ( κ.nonneg' _ ) ( Ne.symm h₁ );
          · exact κ.nonneg' _;
        · field_simp;
          exact ⟨ fun _ _ _ _ _ _ => trivial, by rw [ ← Finset.sum_div _ _ _, div_self ‹_› ], fun _ _ => div_nonneg ( κ.nonneg' _ ) ( Finset.sum_nonneg fun _ _ => κ.nonneg' _ ) ⟩;
      · intro κ; split_ifs <;> simp_all +decide [ Finset.sum_div _ _ _ ] ;
        · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, P3b.CohesionRaw.nonneg' ];
          exact fun _ _ => by split_ifs <;> norm_num;
        · field_simp;
          exact ⟨ fun _ _ _ _ _ _ => trivial, by rw [ ← Finset.sum_div _ _ _, div_self ‹_› ], fun _ _ => div_nonneg ( κ.nonneg' _ ) ( Finset.sum_nonneg fun _ _ => κ.nonneg' _ ) ⟩
