/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: db334b2f-b12f-4374-9b84-cc0cb62173b6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of "Cohesion-Sensitive Power Indices — File 3a: Probabilistic Representation".
This module defines cooperative games, cohesion structures, and values.
It proves Proposition 2.7: Any value satisfying Linearity and Dummy admits a probabilistic representation
in terms of marginal contributions. The proof constructs the representation by factoring the value
through the space of marginal contributions, using the fact that the kernel of the marginal contribution map
consists exactly of the dummy players.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise

abbrev P3a.Player (n : ℕ) := Fin n
def P3a.N (n : ℕ) : Finset (P3a.Player n) := Finset.univ
def P3a.coalitionsWithout (n : ℕ) (i : P3a.Player n) :
    Finset (Finset (P3a.Player n)) :=
  ((P3a.N n).erase i).powerset

structure P3a.Game (n : ℕ) where
  payoff : Finset (P3a.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (P3a.Game n)
    (fun _ => Finset (P3a.Player n) → ℝ) := ⟨P3a.Game.payoff⟩
@[simp] lemma P3a.Game.empty (n : ℕ) (v : P3a.Game n) : v ∅ = 0 := v.empty'

noncomputable instance (n : ℕ) : Add (P3a.Game n) :=
  ⟨fun v w => { payoff := fun S => v S + w S, empty' := by simp [v.empty', w.empty'] }⟩
noncomputable instance (n : ℕ) : SMul ℝ (P3a.Game n) :=
  ⟨fun a v => { payoff := fun S => a * v S, empty' := by simp [v.empty'] }⟩

def P3a.marginalContribution (n : ℕ) (i : P3a.Player n)
    (v : P3a.Game n) (S : Finset (P3a.Player n)) : ℝ :=
  v (insert i S) - v S

def P3a.IsDummy (n : ℕ) (v : P3a.Game n) (i : P3a.Player n) : Prop :=
  ∀ S : Finset (P3a.Player n), i ∉ S → P3a.marginalContribution n i v S = 0

structure P3a.CohesionRaw (n : ℕ) where
  coh : Finset (P3a.Player n) → ℝ
  empty' : coh ∅ = 0
  nonneg' : ∀ S : Finset (P3a.Player n), 0 ≤ coh S

instance (n : ℕ) : CoeFun (P3a.CohesionRaw n)
    (fun _ => Finset (P3a.Player n) → ℝ) := ⟨P3a.CohesionRaw.coh⟩

def P3a.IsAdmissible (n : ℕ) (κ : P3a.CohesionRaw n) : Prop :=
  ∀ i : P3a.Player n, ∃ S : Finset (P3a.Player n), i ∈ S ∧ 0 < κ S

structure P3a.CohesionStructure (n : ℕ) extends P3a.CohesionRaw n where
  admissible' : P3a.IsAdmissible n toCohesionRaw

/-- A value assigns to each (game, cohesion) pair a payoff vector. -/
structure P3a.Value (n : ℕ) where
  F : P3a.Game n → P3a.CohesionStructure n → P3a.Player n → ℝ

def P3a.AxiomLinearity {n : ℕ} (V : P3a.Value n) : Prop :=
  ∀ (κ : P3a.CohesionStructure n) (v w : P3a.Game n)
    (lam mu : ℝ) (i : P3a.Player n),
    V.F (lam • v + mu • w) κ i = lam * V.F v κ i + mu * V.F w κ i

def P3a.AxiomDummy {n : ℕ} (V : P3a.Value n) : Prop :=
  ∀ (v : P3a.Game n) (i : P3a.Player n),
    P3a.IsDummy n v i → ∀ κ : P3a.CohesionStructure n, V.F v κ i = 0

/-- Helper: For any prescribed marginal contributions (Δᵢv(S))_{S⊆N\{i}},
    there exists a game v realizing them.
    Construction: define v(T) = Δᵢv(T\{i}) if i ∈ T, v(T) = 0 if i ∉ T.
    This gives Δᵢv(S) = v(S∪{i}) - v(S) = prescribed(S) - 0 = prescribed(S)
    for S with i ∉ S. -/
theorem P3a.marginals_surjective {n : ℕ} (i : P3a.Player n)
    (target : Finset (P3a.Player n) → ℝ) :
    ∃ v : P3a.Game n, ∀ S : Finset (P3a.Player n), i ∉ S →
      P3a.marginalContribution n i v S = target S := by
  -- Define the game v such that for any coalition S not containing i, v(S ∪ {i}) = target S and v(S) = 0.
  use ⟨fun S => if i ∈ S then target (S.erase i) else 0, by
    -- The empty set does not contain any players, so the condition i ∈ ∅ is false. Therefore, the function returns 0.
    simp [Finset.notMem_empty]⟩
  generalize_proofs at *;
  -- By definition of marginal contribution, we have:
  intro S hi
  simp [P3a.marginalContribution, hi]

/-- Proposition 2.7: Marginal-contribution representation.

    Any value satisfying Linearity and Dummy admits a representation
      Fᵢ(v, κ) = ∑_{S ⊆ N\{i}} wᵢ^κ(S) · Δᵢv(S)
    for some real coefficients wᵢ^κ(S).

    PROOF:
    Fix κ and i. By Linearity, v ↦ Fᵢ(v,κ) is linear on G^N.
    By Dummy, it vanishes whenever all marginal contributions are zero.
    The map Tᵢ: v ↦ (Δᵢv(S))_S is linear with kernel = {dummies}.
    Since Fᵢ(·,κ) vanishes on ker Tᵢ, it factors through im Tᵢ = ℝ^{2^{n-1}}
    (surjectivity: given any target marginals, construct v realizing them).
    The induced linear functional on ℝ^{2^{n-1}} gives the coefficients. -/
theorem P3a.probabilistic_representation
    {n : ℕ} (V : P3a.Value n)
    (hLin : P3a.AxiomLinearity V)
    (hDummy : P3a.AxiomDummy V) :
    ∃ (w : P3a.CohesionStructure n → P3a.Player n →
            Finset (P3a.Player n) → ℝ),
      ∀ (v : P3a.Game n) (κ : P3a.CohesionStructure n)
        (i : P3a.Player n),
        V.F v κ i =
          ∑ S ∈ P3a.coalitionsWithout n i,
            (w κ i S) * (P3a.marginalContribution n i v S) := by
  -- Fix a coalition structure κ and a player i. We need to find coefficients w such that V.F v κ i = ∑ S ∈ P3a.coalitionsWithout n i, w κ i S * P3a.marginalContribution n i v S.
  have h_coeff : ∀ κ : P3a.CohesionStructure n, ∀ i : P3a.Player n, ∃ w : Finset (P3a.Player n) → ℝ, ∀ v : P3a.Game n, V.F v κ i = ∑ S ∈ P3a.coalitionsWithout n i, w S * P3a.marginalContribution n i v S := by
    -- By the properties of linear functionals, there exists a unique linear functional $f$ such that $V.F v κ i = f(v)$ for all $v$.
    intro κ i
    obtain ⟨f, hf⟩ : ∃ f : (Finset (P3a.Player n) → ℝ) →ₗ[ℝ] ℝ, ∀ v : P3a.Game n, V.F v κ i = f (fun S => P3a.marginalContribution n i v S) := by
      have h_well_defined : ∀ v w : P3a.Game n, (∀ S : Finset (P3a.Player n), i∉S → P3a.marginalContribution n i v S = P3a.marginalContribution n i w S) → V.F v κ i = V.F w κ i := by
        intro v w h_eq_marginal;
        -- By Linearity, $v \mapsto F_i(v, \kappa)$ is linear on $G^N$.
        have h_linear : ∀ (v w : P3a.Game n) (lam mu : ℝ), V.F (lam • v + mu • w) κ i = lam * V.F v κ i + mu * V.F w κ i := by
          exact fun v w lam mu => hLin κ v w lam mu i;
        -- By Dummy, $F_i(v, \kappa) = 0$ whenever all marginal contributions are zero.
        have h_dummy : ∀ (v : P3a.Game n), (∀ S : Finset (P3a.Player n), i∉S → P3a.marginalContribution n i v S = 0) → V.F v κ i = 0 := by
          exact fun v hv => hDummy v i hv κ;
        contrapose! h_dummy;
        use (1 : ℝ) • v + (-1 : ℝ) • w;
        simp_all +decide [ sub_eq_zero ];
        refine' ⟨ _, _ ⟩;
        · intro S hi; specialize h_eq_marginal S hi; simp_all +decide [ P3a.marginalContribution ] ;
          convert sub_eq_zero.mpr h_eq_marginal using 1 ; ring!;
          exact show ( 1 * v.payoff ( Insert.insert i S ) + -1 * w.payoff ( Insert.insert i S ) ) - ( 1 * v.payoff S + -1 * w.payoff S ) = v.payoff ( Insert.insert i S ) + ( -v.payoff S - w.payoff ( Insert.insert i S ) ) + w.payoff S by ring;
        · exact fun h => h_dummy <| by linarith;
      have h_well_defined : ∀ f : Finset (P3a.Player n) → ℝ, ∃ v : P3a.Game n, ∀ S : Finset (P3a.Player n), i∉S → P3a.marginalContribution n i v S = f S := by
        exact?;
      have h_linear : ∀ (f g : Finset (P3a.Player n) → ℝ) (a b : ℝ), V.F (Classical.choose (h_well_defined (a • f + b • g))) κ i = a * V.F (Classical.choose (h_well_defined f)) κ i + b * V.F (Classical.choose (h_well_defined g)) κ i := by
        intros f g a b
        have h_eq : ∀ S : Finset (P3a.Player n), i∉S → P3a.marginalContribution n i (a • Classical.choose (h_well_defined f) + b • Classical.choose (h_well_defined g)) S = a • P3a.marginalContribution n i (Classical.choose (h_well_defined f)) S + b • P3a.marginalContribution n i (Classical.choose (h_well_defined g)) S := by
          intros S hiS
          simp [P3a.marginalContribution];
          exact show ( a * Classical.choose ( h_well_defined f ) ( Insert.insert i S ) + b * Classical.choose ( h_well_defined g ) ( Insert.insert i S ) ) - ( a * Classical.choose ( h_well_defined f ) S + b * Classical.choose ( h_well_defined g ) S ) = a * ( Classical.choose ( h_well_defined f ) ( Insert.insert i S ) - Classical.choose ( h_well_defined f ) S ) + b * ( Classical.choose ( h_well_defined g ) ( Insert.insert i S ) - Classical.choose ( h_well_defined g ) S ) by ring;
        convert hLin κ ( Classical.choose ( h_well_defined f ) ) ( Classical.choose ( h_well_defined g ) ) a b i using 1;
        apply_assumption;
        intro S hi; rw [ Classical.choose_spec ( h_well_defined ( a • f + b • g ) ) S hi, h_eq S hi ] ; simp +decide [ mul_add, add_mul, mul_assoc, mul_comm, mul_left_comm ] ;
        rw [ Classical.choose_spec ( h_well_defined f ) S hi, Classical.choose_spec ( h_well_defined g ) S hi ];
      have h_linear : ∃ (f : (Finset (P3a.Player n) → ℝ) →ₗ[ℝ] ℝ), ∀ f' : Finset (P3a.Player n) → ℝ, f f' = V.F (Classical.choose (h_well_defined f')) κ i := by
        refine' ⟨ { toFun := fun f' => V.F ( Classical.choose ( h_well_defined f' ) ) κ i, map_add' := _, map_smul' := _ }, _ ⟩;
        exacts [ fun f g => by simpa using h_linear f g 1 1, fun m f => by simpa using h_linear f f m 0, fun f => rfl ];
      obtain ⟨ f, hf ⟩ := h_linear;
      use f;
      intro v; rw [ hf ] ; exact ‹∀ ( v w : P3a.Game n ), ( ∀ S : Finset ( P3a.Player n ), i∉S → P3a.marginalContribution n i v S = P3a.marginalContribution n i w S ) → V.F v κ i = V.F w κ i› v ( Classical.choose ( h_well_defined fun S => P3a.marginalContribution n i v S ) ) fun S hS => by simp +decide [ Classical.choose_spec ( h_well_defined fun S => P3a.marginalContribution n i v S ) S hS ] ;
    -- Since $f$ is a linear functional, there exists a unique vector $w$ such that $f(x) = \sum_{S} w_S x_S$ for all $x$.
    obtain ⟨w, hw⟩ : ∃ w : Finset (P3a.Player n) → ℝ, ∀ x : Finset (P3a.Player n) → ℝ, f x = ∑ S, w S * x S := by
      use fun S => f (fun T => if T = S then 1 else 0);
      intro x; rw [ show x = ∑ S, x S • ( fun T => if T = S then 1 else 0 : Finset ( P3a.Player n ) → ℝ ) by ext T; simp +decide [ Finset.sum_ite_eq' ] ] ; simp +decide [ mul_comm ] ;
    use fun S => if i ∈ S then 0 else w S;
    intro v; rw [ hf, hw ] ; simp +decide [ Finset.sum_ite, Finset.filter_ne', Finset.filter_eq' ] ;
    rw [ ← Finset.sum_subset ( show Finset.filter ( fun S => i ∉ S ) ( P3a.coalitionsWithout n i ) ⊆ Finset.univ from Finset.subset_univ _ ) ];
    simp +contextual [ P3a.marginalContribution ];
    intro x hx; by_cases hi : i ∈ x <;> simp_all +decide [ P3a.coalitionsWithout ] ;
    exact False.elim <| hx <| fun y hy => Finset.mem_erase_of_ne_of_mem ( by aesop ) <| Finset.mem_univ _;
  exact ⟨ fun κ i => Classical.choose ( h_coeff κ i ), fun v κ i => Classical.choose_spec ( h_coeff κ i ) v ⟩
