/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e0bd247a-04f4-434f-8fbb-413e2c5fec02

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines the simplified cohesion-sensitive power indices framework (File 3d).
It includes definitions for `P3d.Game`, `P3d.marginalContribution`, and `P3d.banzhafValue`.
It proves two assembly theorems:
1. `P3d.banzhaf_assembly`: Shows that if a value F is represented by weights p, and p is uniform (1/2^{n-1}), then F is the Banzhaf value.
2. `P3d.shapley_assembly`: Shows that if F is represented by weights p, and p depends only on coalition size (α_k), then F is a weighted sum of marginal contributions with weights α_k.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev P3d.Player (n : ℕ) := Fin n

def P3d.N (n : ℕ) : Finset (P3d.Player n) := Finset.univ

def P3d.coalitionsWithout (n : ℕ) (i : P3d.Player n) :
    Finset (Finset (P3d.Player n)) :=
  ((P3d.N n).erase i).powerset

structure P3d.Game (n : ℕ) where
  payoff : Finset (P3d.Player n) → ℝ
  empty' : payoff ∅ = 0

instance (n : ℕ) : CoeFun (P3d.Game n)
    (fun _ => Finset (P3d.Player n) → ℝ) := ⟨P3d.Game.payoff⟩

def P3d.marginalContribution (n : ℕ) (i : P3d.Player n)
    (v : P3d.Game n) (S : Finset (P3d.Player n)) : ℝ :=
  v (insert i S) - v S

def P3d.banzhafValue (n : ℕ) (v : P3d.Game n) (i : P3d.Player n) : ℝ :=
  ∑ S ∈ P3d.coalitionsWithout n i,
    ((1 : ℝ) / ((2 : ℝ) ^ (n - 1))) * (P3d.marginalContribution n i v S)

theorem P3d.banzhaf_assembly
    {n : ℕ}
    (F : P3d.Game n → P3d.Player n → ℝ)
    (p : P3d.Player n → Finset (P3d.Player n) → ℝ)
    -- F is represented via p
    (hRepr : ∀ (v : P3d.Game n) (i : P3d.Player n),
      F v i = ∑ S ∈ P3d.coalitionsWithout n i,
        (p i S) * (P3d.marginalContribution n i v S))
    -- p is uniform
    (hUnif : ∀ (i : P3d.Player n) (S : Finset (P3d.Player n)),
      S ∈ P3d.coalitionsWithout n i →
        p i S = (1 : ℝ) / ((2 : ℝ) ^ (n - 1))) :
    ∀ (v : P3d.Game n) (i : P3d.Player n),
      F v i = P3d.banzhafValue n v i := by
  -- Apply hUnif to each term in the sum from hRepr.
  intros v i
  rw [hRepr]
  apply Finset.sum_congr rfl
  intro S hS
  rw [hUnif i S hS]

theorem P3d.shapley_assembly
    {n : ℕ}
    (F : P3d.Game n → P3d.Player n → ℝ)
    (p : P3d.Player n → Finset (P3d.Player n) → ℝ)
    (α : ℕ → ℝ)
    -- F is represented via p
    (hRepr : ∀ (v : P3d.Game n) (i : P3d.Player n),
      F v i = ∑ S ∈ P3d.coalitionsWithout n i,
        (p i S) * (P3d.marginalContribution n i v S))
    -- p equals size weights
    (hBench : ∀ (i : P3d.Player n) (S : Finset (P3d.Player n)),
      S ∈ P3d.coalitionsWithout n i →
        p i S = α S.card) :
    ∀ (v : P3d.Game n) (i : P3d.Player n),
      F v i = ∑ S ∈ P3d.coalitionsWithout n i,
        (α S.card) * (P3d.marginalContribution n i v S) := by
  -- By substituting hBench into hRepr, we can replace p i S with α S.card in the sum.
  intros v i
  rw [hRepr]
  apply Finset.sum_congr rfl
  intro S hS
  rw [hBench i S hS]
