/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: eabe0391-3da4-4a9f-8981-101b7eb10903

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines a simple game and its properties (monotonicity, simple game), and proves key lemmas about marginal contributions in monotone simple games. Specifically, it proves that in a monotone simple game, the marginal contribution of a player to any coalition is either 0 or 1. This bridges the gap between the paper's formulation and the verified statement.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev PBr.Player (n : ℕ) := Fin n
def PBr.N (n : ℕ) : Finset (PBr.Player n) := Finset.univ
def PBr.coalitionsWithout (n : ℕ) (i : PBr.Player n) :
    Finset (Finset (PBr.Player n)) :=
  ((PBr.N n).erase i).powerset

structure PBr.Game (n : ℕ) where
  payoff : Finset (PBr.Player n) → ℝ
  empty' : payoff ∅ = 0
instance (n : ℕ) : CoeFun (PBr.Game n)
    (fun _ => Finset (PBr.Player n) → ℝ) := ⟨PBr.Game.payoff⟩

def PBr.marginalContribution (n : ℕ) (i : PBr.Player n)
    (v : PBr.Game n) (S : Finset (PBr.Player n)) : ℝ :=
  v (insert i S) - v S

def PBr.IsSimpleGame (n : ℕ) (v : PBr.Game n) : Prop :=
  (∀ S : Finset (PBr.Player n), v S = 0 ∨ v S = 1) ∧ v (PBr.N n) = 1

/-- A simple game is monotone if v(S) = 1 implies v(T) = 1 for all T ⊇ S. -/
def PBr.IsMonotone (n : ℕ) (v : PBr.Game n) : Prop :=
  ∀ S T : Finset (PBr.Player n), S ⊆ T → v S = 1 → v T = 1

/-- A monotone simple game is a simple game that is also monotone.
    This is the standard notion in cooperative game theory. -/
def PBr.IsMonotoneSimpleGame (n : ℕ) (v : PBr.Game n) : Prop :=
  PBr.IsSimpleGame n v ∧ PBr.IsMonotone n v

theorem PBr.marginal_in_neg1_0_1 {n : ℕ} (v : PBr.Game n)
    (hv : PBr.IsSimpleGame n v) (i : PBr.Player n)
    (S : Finset (PBr.Player n)) :
    PBr.marginalContribution n i v S = -1 ∨
    PBr.marginalContribution n i v S = 0 ∨
    PBr.marginalContribution n i v S = 1 := by
  -- By definition of $PBr.marginalContribution$, we know that $v (insert i S) - v S$ is either $-1$, $0$, or $1$.
  have h_diff : v (insert i S) - v S = -1 ∨ v (insert i S) - v S = 0 ∨ v (insert i S) - v S = 1 := by
    have h_values : ∀ T : Finset (PBr.Player n), v T = 0 ∨ v T = 1 := by
      -- By definition of PBr.IsSimpleGame, we know that for any coalition T, v(T) is either 0 or 1.
      apply hv.left
    -- By considering all possible cases for v(insert i S) and v(S), we can conclude that their difference is always -1, 0, or 1.
    cases h_values (insert i S) <;> cases h_values S <;> simp [*];
  -- Apply the hypothesis `h_diff` to conclude the proof.
  apply h_diff

theorem PBr.marginal_nonneg_of_monotone {n : ℕ} (v : PBr.Game n)
    (hv : PBr.IsMonotoneSimpleGame n v) (i : PBr.Player n)
    (S : Finset (PBr.Player n)) :
    PBr.marginalContribution n i v S ≥ 0 := by
  -- Since $v$ is monotone, we have $v(S) \leq v(S \cup \{i\})$.
  have h_monotone : v S ≤ v (insert i S) := by
    -- Since $S \subseteq S \cup \{i\}$, we can apply the monotonicity property of $v$.
    have h_subset : S ⊆ insert i S := by
      -- By definition of insert, every element of S is in insert i S.
      apply Finset.subset_insert;
    -- Since $v$ is a monotone simple game, we have $v(S) \leq v(T)$ for any $S \subseteq T$.
    have h_monotone : ∀ S T : Finset (PBr.Player n), S ⊆ T → v S ≤ v T := by
      intros S T hST
      by_cases hS : v S = 1
      generalize_proofs at *; (
      have := hv.2 S T hST; aesop;);
      cases hv.1.1 S <;> cases hv.1.1 T <;> aesop;
    exact h_monotone _ _ h_subset;
  exact sub_nonneg_of_le h_monotone

theorem PBr.marginal_zero_or_one_of_monotone {n : ℕ} (v : PBr.Game n)
    (hv : PBr.IsMonotoneSimpleGame n v) (i : PBr.Player n) :
    ∀ S ∈ PBr.coalitionsWithout n i,
      PBr.marginalContribution n i v S = 1 ∨
      PBr.marginalContribution n i v S = 0 := by
  intro S hS
  have h_marginal : PBr.marginalContribution n i v S ≥ 0 := by
    -- Apply the theorem that states the marginal contribution is non-negative for a monotone simple game.
    apply PBr.marginal_nonneg_of_monotone v hv i S
  have h_marginal_values : PBr.marginalContribution n i v S = -1 ∨ PBr.marginalContribution n i v S = 0 ∨ PBr.marginalContribution n i v S = 1 := by
    -- Apply the theorem that states the marginal contribution is in {-1, 0, 1} for any simple game.
    apply PBr.marginal_in_neg1_0_1 v hv.1 i S;
  grind
